version: '3.8'

services:
    symfony:
        build: app
        container_name: symfony_docker
        ports:
            - "8245:80"
        volumes:
            - ./app/vhosts:/etc/apache2/sites-enabled
            - .project/:/var/www/project
        restart: always
        networks:
            - dev

    websocket:
        image: php:8.1.2-cli
        container_name: websocket_docker
        env_file:
            - './websocket/.env'
        volumes:
            - ./websocket:/var/www/html
        ports:
            - "9090:9090"
        command: php /var/www/html/src/wamp-server.php


    maildev:
        image: maildev/maildev
        container_name: maildev_docker
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - dev

    db:
        image: mariadb
        container_name: mariadb_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

networks:
    dev:

volumes:
    db-data:
